# Secret ranks counters are not shown if not in deck
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''if rank_tallies[rank_name_mapping[i]] ~= 0 or not SMODS.Ranks[rank_name_mapping[i]].in_pool or SMODS.Ranks[rank_name_mapping[i]]:in_pool({suit=''}) then'''
position = "at"
match_indent = true
payload = '''
if rank_tallies[rank_name_mapping[i]] ~= 0 or ((not SMODS.Ranks[rank_name_mapping[i]].in_pool or SMODS.Ranks[rank_name_mapping[i]]:in_pool({suit=''})) and not SMODS.Ranks[rank_name_mapping[i]].secret) then
'''

# Secret ranks doesn't appear in challenges Full Deck tab
[[patches]]
[patches.pattern]
target = '''functions/UI_definitions.lua'''
pattern = '''if type(SMODS.Suits[v.suit].in_pool) == 'function' and not SMODS.Suits[v.suit]:in_pool({initial_deck = true, rank = v.value}) then'''
position = "before"
match_indent = true
payload = '''
if SMODS.Ranks[v.value].secret then
    keep = false
end
